---
title: "Introduction"
author: "Niklaas Baudet von Gersdorff"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The package provides a function `tidy_ext_tracks` to clean the data. It further
provides a function `hurricane` that retrieves a single storm from the data.

```{r}
library(geomhurricane)

hurricanes <- tidy_ext_tracks(ext_tracks)
ike <- hurricane(hurricanes, "Ike-2008")
```

```{r}
library(ggmap)
library(ggplot2)

map_data <- get_map("Louisiana", zoom = 6, maptype = "toner-background")
base_map <- ggmap(map_data, extent = "device")

base_map +
  geom_hurricane(data = ike,
                  mapping =
                    aes(x = longitude, y = latitude,
                                 r_ne = ne,
                                 r_se = se,
                                 r_sw = sw,
                                 r_nw = nw,
                                 fill = as.factor(wind_speed))) +
  scale_color_manual(name = "Wind speed (kts)",
                     values = c("red", "orange", "yellow")) +
  scale_fill_manual(name = "Wind speed (kts)",
                    values = c("red", "orange", "yellow"))
```
